# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180725_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_price',
        ),
    ]
