# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180726_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_zipcode',
            field=models.CharField(default='11111', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_zipcode',
            field=models.CharField(default='11111', max_length=5),
            preserve_default=False,
        ),
    ]
