# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20180726_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_order',
            field=models.IntegerField(default=1),
        ),
    ]
